Add exclude and fail-fast for task 3

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -5,9 +5,13 @@ on: [push, workflow_dispatch]
 jobs:
   test:
     strategy:
+      fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest]
+        os: [ubuntu-latest, windows-latest,macos-latest]
         python-version: ["3.10","3.11","3.12"]
+        exclude:
+          - os: windows-latest
+            python-version: "3.10"
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout code
@@ -20,3 +24,9 @@ jobs:
       
       - name: Show Python version 
         run: python --version
+      
+      - name: Force failure in on job (For demo)
+        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
+        run: |
+          echo "Failing this Job intentionally"
+          exit 1
